name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copia arquivos para o servidor via SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
        touch .env
        echo "GROQ_API_KEY=$GROQ_API_KEY" > .env
        echo "API_TOKEN=$API_TOKEN" > .env
        rsync -avz --rsync-path="sudo rsync" -e 'ssh -o StrictHostKeyChecking=no' ./ $SSH_USER@$SSH_HOST:/home/ubuntu/tcc_bd/tcc_bd

    - name: Deploy Application
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
          cd /home/ubuntu/tcc_bd/tcc_bd
          sudo docker compose down
          sudo docker compose up -d --build
        EOF
